project_name: event-generator
before:
  hooks:
    - make prepare
builds:
  - id: "event-generator"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: .
    flags:
      - -buildmode=pie
    env:
      - CGO_ENABLED=0
    binary: event-generator

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "falcosecurity/event-generator:main-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=main"
    extra_files:
      - .git
      - cmd
      - pkg
      - events
      - tools
      - go.mod
      - go.sum
      - main.go
      - Makefile
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - "falcosecurity/event-generator:main-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=main"
    extra_files:
      - .git
      - cmd
      - pkg
      - events
      - tools
      - go.mod
      - go.sum
      - main.go
      - Makefile
docker_manifests:
  - name_template: falcosecurity/event-generator:main
    image_templates:
      - falcosecurity/event-generator:main-amd64
      - falcosecurity/event-generator:main-arm64v8

# Skip the GitHub release for the main branch workflow
release:
  disable: true
