apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-event-generator-deployment
  labels:
    app: falco-event-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falco-event-generator
  template:
    metadata:
      labels:
        app: falco-event-generator
    spec:
      serviceAccount: falco-event-generator
      containers:
      - name: falco-event-generator
        image: falcosecurity/event-generator
        imagePullPolicy: Always
        command: ["/bin/event-generator", "run", "--loop"]
        env:
        - name: FALCO_EVENT_GENERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
