apiVersion: batch/v1
kind: Job
metadata:
  name: falco-event-generator
spec:
  template:
    spec:
      containers:
      - name: event-generator
        image: falcosecurity/event-generator
        command: ["/bin/event-generator", "run"]
      restartPolicy: Never
  backoffLimit: 4
