apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: write-privileges-role
  labels:
    app.kubernetes.io/name: write-privileges-role
    app.kubernetes.io/part-of: falco-event-generator
    falco.org/rule: ClusterRole-With-Write-Privileges-Created
rules:
- apiGroups:
    - ""
  resources:
    - "pods"
  verbs:
    - create
