apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-exec-role
  labels:
    app.kubernetes.io/name: pod-exec-role
    app.kubernetes.io/part-of: falco-event-generator
    falco.org/rule: ClusterRole-With-Pod-Exec-Created
rules:
- apiGroups:
    - ""
  resources:
    - "pods/exec"
  verbs:
    - get
