apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wildcard-resources-role
  labels:
    app.kubernetes.io/name: wildcard-resources-role
    app.kubernetes.io/part-of: falco-event-generator
    falco.org/rule: ClusterRole-With-Wildcard-Created
rules:
- apiGroups:
    - ""
  resources:
    - "*"
  verbs:
    - get
