apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    app.kubernetes.io/name: nodeport-service
    app.kubernetes.io/part-of: falco-event-generator
    falco.org/rule: Create-NodePort-Service
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: busybox
