apiVersion: v1
kind: Service
metadata:
  name: vanilla-service
  labels:
    app.kubernetes.io/name: vanilla-service
    app.kubernetes.io/part-of: falco-event-generator
    falco.org/rule: K8s-Service-Created
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: busybox