apiVersion: v1
kind: ConfigMap
metadata:
  name: vanilla-configmap
  labels:
    app.kubernetes.io/name: vanilla-configmap
    app.kubernetes.io/part-of: falco-event-generator
    falco.org/rule: K8s-ConfigMap-Created
data:
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true