name: Publish Main

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "amd64,arm64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.1

      - name: Run GoReleaser for Main Branch
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: v1.10.3
          args: release --snapshot --rm-dist --timeout 60m --config .goreleaser.main.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: main
